# Use an official Node.js runtime as the base image
FROM node:20.0.0-alpine AS backend

# Set the working directory in the container
WORKDIR /app/quirknotes/backend

# Copy package.json and package-lock.json to the working directory
COPY quirknotes/backend/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY quirknotes/backend ./

# Start the application
CMD [ "npm", "start" ]
